name: homepage-dev
on:
  push
  pull_request:
    branches:
      - main

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Get code
          uses: actions/checkout@v3
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 16
        - name: Install dependencies
          run: npm ci
        - name: Run build
          run: npm run build

    deploy:
      needs: build # Ensure the 'build' job is successful before deploying
      runs-on: ubuntu-latest
      steps:
        - name: Get code
          uses: actions/checkout@v3
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 16
        - name: Install dependencies
          run: npm ci
        - name: Run build
          run: npm run build